
["Master Sword Configs - Enable/Disable Songs"]
	#
	#
	# Defines if the Song of Storms in enabled
	enable_song_of_storms = true
	#
	#
	# Defines if the Sun's Song in enabled
	enable_suns_song = true

["Master Sword Configs - Sword Damage Bonus"]
	#
	#
	#**THE DAMAGE VALUES MUST CONTAIN A DECIMAL PLACE. (e.g. 1.0)**
	#
	#
	# (2 + the defined value = sword total damage. (e.g. Goddess Sword does 2 + 2.5 = 4.5 damage by default))
	#
	# Defines the damage bonus for Goddess Sword
	goddess_sword_damage = 2.5
	#
	# Defines the damage bonus for Goddess Longsword
	goddess_longsword_damage = 3.5
	#
	# Defines the damage bonus for White Goddess Sword
	white_goddess_sword_damage = 4.5
	#
	# Defines the damage bonus for Master Sword
	master_sword_damage = 5.5
	#
	# Defines the damage bonus for Tempered Master Sword
	tempered_master_sword_damage = 6.5
	#
	# Defines the damage bonus for Golden Master Sword
	golden_master_sword_damage = 7.5
	#
	# Defines the damage bonus for Fierce Deity Sword
	fierce_deity_sword_damage = 9.0
	#
	# Defines the damage bonus for True Master Sword
	true_master_sword_damage = 8.5
	#
	# Defines the damage bonus for Magic Hammer
	magic_hammer_damage = 6.0

["Master Sword Configs - Sword Durability"]
	#
	#
	#**THE DURABILITY VALUES MUST BE A WHOLE NUMBER/INTEGER. (e.g. 2500)**
	#
	#
	# Defines the durability for Goddess Sword
	goddess_sword_durability = 1300
	#
	# Defines the durability for Goddess Longsword
	goddess_longsword_durability = 1500
	#
	# Defines the durability for White Goddess Sword
	white_goddess_sword_durability = 1700
	#
	# Defines the durability for Master Sword
	master_sword_durability = 1900
	#
	# Defines the durability for Tempered Master Sword
	tempered_master_sword_durability = 2200
	#
	# Defines the durability for Golden Master Sword
	golden_master_sword_durability = 2500
	#
	# Defines the durability for Fierce Deity Sword
	fierce_deity_sword_durability = 3000
	#
	# Defines the durability for True Master Sword
	true_master_sword_durability = 3000
	#
	# Defines the durability for Magic Hammer
	magic_hammer_durability = 2000

["Master Sword Configs - Sword Spin Ability Damage"]
	#
	#
	#**THE DAMAGE VALUES MUST CONTAIN A DECIMAL PLACE. (e.g. 1.0)**
	#
	#
	# Defines the spin attack damage for Master Sword
	spin_damage_master_sword = 10.0
	#
	# Defines the spin attack damage for Tempered Master Sword
	spin_damage_tempered_master_sword = 14.0
	#
	# Defines the spin attack damage for Golden Master Sword
	spin_damage_golden_master_sword = 18.0
	#
	# Defines the spin attack damage for True Master Sword
	spin_damage_true_master_sword = 19.0
	#
	# Defines the spin attack damage for Fierce Deity Sword
	spin_damage_fierce_deity_sword = 20.0

["Master Sword Configs - Sword Beam Damage"]
	#
	#
	#**THE DAMAGE VALUES MUST CONTAIN A DECIMAL PLACE. (e.g. 1.0)**
	#
	#
	# Defines the base beam damage
	base_beam_damage = 5.0
	#
	# Defines the Ciela enhanced beam damage
	enhanced_beam_damage = 8.0

["Master Sword Configs - Magic Staff Configs"]
	#
	#
	#**THE DAMAGE VALUES MUST CONTAIN A DECIMAL PLACE. (e.g. 1.0)**
	#
	#
	# Defines the Fire Rod's magic damage
	fire_rod_damage = 20.0
	#
	# Defines the durability for Fire Rod
	fire_rod_durability = 50
	#
	# Defines the explosion modifier for Fire Rod
	fire_rod_explosion = 1.0
	#
	# Defines if the Fire Rod explosion can cause fires
	fire_rod_cause_fires = true
	#
	# Defines the Ice Rod's magic damage
	ice_rod_damage = 2.0
	#
	# Defines the durability for Ice Rod
	ice_rod_durability = 50
	#
	# Defines if the Ice Rod creates snow on hit blocks
	ice_rod_leave_snow = true

["Master Sword Configs - Magic Meter Configs"]
	#
	#
	# Defines how to render the Magic Meter, Default = false
	# true = ALWAYS
	# false = ONLY WHEN NEEDED
	always_show_magic_meter = false
	#
	#Defines the X position to render the Magic Meter
	magic_meter_position_x = 420
	#
	#Defines the Y position to render the Magic Meter
	magic_meter_position_y = 3

["Master Sword Configs - Goron Merchant Trade Costs"]
	#
	#
	#**Defines the trade costs/results for the Goron Merchant Trade Offers**
	#
	#
	#**Defines the Emerald trade cost for 1 Green Rupee
	trade_emerald_to_rupee = 9
	#
	#Defines the rupee type for the Rupee to Bombchu trade
	trade_rupee_to_bombchu_type = "green_rupee"
	#
	#**Defines the specified Rupee trade cost for 1 Bombchu
	trade_rupee_to_bombchu = 3
	#
	#Defines the rupee type for the Rupee to Green Potion trade
	trade_rupee_to_green_potion_type = "blue_rupee"
	#
	#**Defines the specified Rupee trade cost for 1 Green Potion
	trade_rupee_to_green_potion = 2
	#
	#Defines the rupee type for the Rupee to Lon Lon Milk trade
	trade_lon_lon_milk_to_rupee_type = "green_rupee"
	#
	#**Defines the specified Rupee trade result for 1 Lon Lon Milk
	trade_lon_lon_milk_to_rupee = 4
	#
	#Defines the rupee type for the Rupee to Boomerang trade
	trade_rupee_to_boomerang_type = "blue_rupee"
	#
	#**Defines the specified Rupee trade cost for 1 Boomerang
	trade_rupee_to_boomerang = 3
	#
	#Defines the rupee type for the Rupee to Magic Hammer trade
	trade_rupee_to_magic_hammer_type = "red_rupee"
	#
	#**Defines the specified Rupee trade cost for 1 Magic Hammer
	trade_rupee_to_magic_hammer = 1
	#
	#Defines the rupee type for the Rupee to Hookshot trade
	trade_rupee_to_hookshot_type = "purple_rupee"
	#
	#**Defines the specified Rupee trade cost for 1 Hookshot
	trade_rupee_to_hookshot = 1
	#
	#Defines the rupee type for the Rupee to Fairy Arrows trade
	trade_rupee_to_fairy_arrow_type = "blue_rupee"
	#
	#**Defines the specified Rupee trade cost for 15 Fairy Arrows
	trade_rupee_to_fairy_arrow = 2
	#
	#Defines the rupee type for the Rupee to Dark Hylian Shield trade
	trade_rupee_to_dark_hylian_shield_type = "gold_rupee"
	#
	#**Defines the specified Rupee trade cost for 1 Dark Hylian Shield
	trade_rupee_to_dark_hylian_shield = 2
	#
	#Defines the rupee type for the Rupee to Temple of Time Music disc trade
	trade_rupee_to_temple_of_time_music_disc_type = "red_rupee"
	#
	#**Defines the specified Rupee trade cost for 1 Temple of Time Music disc
	trade_rupee_to_temple_of_time_music_disc = 1

["Master Sword Configs - Rupee Drop Chances"]
	#
	#
	#**Defines the drop chance for Rupees when a monster-type mob is slain by a player
	#
	#
	#**Defines the drop chance percentage for Green Rupee, 10 = 10%
	green_rupee_drop_chance = 10
	#
	#**Defines the drop chance percentage for Blue Rupee
	blue_rupee_drop_chance = 1
	#
	#**Defines the drop chance percentage for Red Rupee
	red_rupee_drop_chance = 0
	#
	#**Defines the drop chance percentage for Purple Rupee
	purple_rupee_drop_chance = 0
	#
	#**Defines the drop chance percentage for Silver Rupee
	silver_rupee_drop_chance = 0
	#
	#**Defines the drop chance percentage for Gold Rupee
	gold_rupee_drop_chance = 0

