
#コアゲームプレイに関する全ての設定項目
[gameplay]
	#戦利品箱で補給船やキャンプを生成するかどうか。 [初期値: true]
	generatesupplyloot = true

#要求システムに関する全ての設定
[requestsystem]
	#Should the request system show debug information in the debug.log? Useful if malfunctioning. [初期値: false]
	enabledebuglogging = false

